apiVersion: apps/v1
kind: Deployment
metadata:
  name: macross-website-company
  namespace: production
spec:
  selector:
    matchLabels:
      app: macross-website-company
  template:
    metadata:
      labels:
        app: macross-website-company
    spec:
      containers:
        - name: macross-website-company
          image: rundcode/macross-blog-documenter-cilsy:1
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: landingpage-service
  namespace: production
spec:
  selector:
    app: macross-website-company
  ports:
    - port: 80
      targetPort: 80